<template>
  <component :is="iconComponent" v-bind="$attrs" :size="size" />
</template>

<script>
import { defineComponent } from 'vue';
import {
  CalendarDays,
  CalendarRange,
  Activity,
  Database,
  Search,
  Globe,
  Code,
  SquareTerminal,
  MoreHorizontal,
  Smartphone,
  Monitor,
  Settings,
  Wrench,
  Timer,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Plus,
  Minus,
  Trash2,
  Edit,
  Save,
  X,
  Eye,
  EyeOff,
  Camera,
  Copy,
  Download,
  Upload,
  RefreshCw,
  Check,
  AlertTriangle,
  CircleAlert,
  Info,
  HelpCircle,
  Palette,
  Folder,
  File,
  List,
  BarChart2,
  Clock,
  Play,
  Pause,
  Square,
  ArrowUp,
  ArrowDown,
  Tag,
  Sun,
  Moon,
  GripVertical,
  House,
  CircleCheck,
  History,
} from 'lucide-vue-next';

// Map FontAwesome icon names used across the codebase to Lucide equivalents
const iconMap = {
  'calendar-day': CalendarDays,
  'calendar-week': CalendarRange,
  calendar: Calendar,
  'calendar-alt': Calendar,
  stream: Activity,
  database: Database,
  search: Search,
  globe: Globe,
  code: Code,
  terminal: SquareTerminal,
  'ellipsis-h': MoreHorizontal,
  mobile: Smartphone,
  desktop: Monitor,
  cog: Settings,
  cogs: Settings,
  tools: Wrench,
  stopwatch: Timer,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  plus: Plus,
  minus: Minus,
  trash: Trash2,
  'trash-alt': Trash2,
  edit: Edit,
  'pencil-alt': Edit,
  save: Save,
  times: X,
  close: X,
  eye: Eye,
  'eye-slash': EyeOff,
  camera: Camera,
  copy: Copy,
  download: Download,
  upload: Upload,
  sync: RefreshCw,
  'sync-alt': RefreshCw,
  check: Check,
  'exclamation-triangle': AlertTriangle,
  'exclamation-circle': CircleAlert,
  'info-circle': Info,
  'question-circle': HelpCircle,
  palette: Palette,
  folder: Folder,
  file: File,
  list: List,
  'chart-bar': BarChart2,
  clock: Clock,
  play: Play,
  pause: Pause,
  stop: Square,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  tag: Tag,
  tags: Tag,
  sun: Sun,
  moon: Moon,
  bars: GripVertical,
  home: House,
  'circle-check': CircleCheck,
  history: History,
};

export default defineComponent({
  name: 'Icon',
  inheritAttrs: false,
  props: {
    name: { type: String, required: true },
    size: { type: [Number, String], default: 16 },
  },
  computed: {
    iconComponent() {
      return iconMap[this.name] || HelpCircle;
    },
  },
});
</script>
