export const ACTIVITY_VISUALIZATION = {
  BROWSER_PLUGIN_PROMPT: 'browser_plugin_prompt',
  EDITOR_PLUGIN_PROMPT: 'editor_plugin_prompt',
  TOP_APPS: 'top_apps',
  TOP_DOMAINS: 'top_domains',
  TOP_URLS: 'top_urls',
  TOP_BROWSER_TITLES: 'top_browser_titles',
  TOP_CATEGORIES: 'top_categories',
  CATEGORY_DONUT: 'category_donut',
  TIMELINE_BARCHART: 'timeline_barchart',
} as const;

export type ActivityVisualizationType =
  (typeof ACTIVITY_VISUALIZATION)[keyof typeof ACTIVITY_VISUALIZATION];

const APP_ACTIVITY_VISUALIZATIONS = new Set<string>([ACTIVITY_VISUALIZATION.TOP_APPS]);

export const BROWSER_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ACTIVITY_VISUALIZATION.TOP_DOMAINS,
  ACTIVITY_VISUALIZATION.TOP_URLS,
  ACTIVITY_VISUALIZATION.TOP_BROWSER_TITLES,
]);

export const CATEGORY_PERIOD_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ACTIVITY_VISUALIZATION.TIMELINE_BARCHART,
]);

export const CATEGORY_TOP_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ACTIVITY_VISUALIZATION.TOP_CATEGORIES,
  ACTIVITY_VISUALIZATION.CATEGORY_DONUT,
]);

export const WINDOW_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ...APP_ACTIVITY_VISUALIZATIONS,
  ...CATEGORY_TOP_ACTIVITY_VISUALIZATIONS,
  ...CATEGORY_PERIOD_ACTIVITY_VISUALIZATIONS,
]);

const DASHBOARD_DTO_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ...APP_ACTIVITY_VISUALIZATIONS,
  ...CATEGORY_TOP_ACTIVITY_VISUALIZATIONS,
  ...CATEGORY_PERIOD_ACTIVITY_VISUALIZATIONS,
  ...BROWSER_ACTIVITY_VISUALIZATIONS,
]);

const STANDALONE_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ACTIVITY_VISUALIZATION.EDITOR_PLUGIN_PROMPT,
]);

export const ACTIVITY_PLUGIN_PROMPT_VISUALIZATIONS = new Set<string>([
  ACTIVITY_VISUALIZATION.BROWSER_PLUGIN_PROMPT,
  ACTIVITY_VISUALIZATION.EDITOR_PLUGIN_PROMPT,
]);

export const PUBLIC_ACTIVITY_VISUALIZATIONS = new Set<string>([
  ...DASHBOARD_DTO_ACTIVITY_VISUALIZATIONS,
  ...STANDALONE_ACTIVITY_VISUALIZATIONS,
]);

export const QUERY_BACKED_ACTIVITY_VISUALIZATIONS = new Set<string>(
  DASHBOARD_DTO_ACTIVITY_VISUALIZATIONS
);

export const ACTIVITY_VISUALIZATION_TITLES: Record<string, string> = {
  [ACTIVITY_VISUALIZATION.BROWSER_PLUGIN_PROMPT]: 'Browser Plugin',
  [ACTIVITY_VISUALIZATION.EDITOR_PLUGIN_PROMPT]: 'Editor Plugin',
  [ACTIVITY_VISUALIZATION.TOP_APPS]: 'Top Applications',
  [ACTIVITY_VISUALIZATION.TOP_DOMAINS]: 'Top Browser Domains',
  [ACTIVITY_VISUALIZATION.TOP_URLS]: 'Top Browser URLs',
  [ACTIVITY_VISUALIZATION.TOP_BROWSER_TITLES]: 'Top Browser Titles',
  [ACTIVITY_VISUALIZATION.TOP_CATEGORIES]: 'Top Categories',
  [ACTIVITY_VISUALIZATION.CATEGORY_DONUT]: 'Pie Chart',
  [ACTIVITY_VISUALIZATION.TIMELINE_BARCHART]: 'Timeline',
};
